import type { TargetPlatform } from '../schema'
import { PLATFORM_VALIDATION_RULES, type PlatformRules } from '../validation/platform-rules'

export interface PlatformCompatibilityRow {
  platform: TargetPlatform
  status: 'Primary' | 'Beta'
  docsBasis: string
  manifest: string
  hooks: string
  mcp: string
  instructions: string
  verification: string
}

const ALL_TARGET_PLATFORMS: TargetPlatform[] = [
  'claude-code',
  'cursor',
  'codex',
  'opencode',
  'github-copilot',
  'openhands',
  'warp',
  'gemini-cli',
  'roo-code',
  'cline',
  'amp',
]

const PRIMARY_TARGETS = new Set<TargetPlatform>(['claude-code', 'cursor', 'codex', 'opencode'])
const RELEASE_SMOKE_TARGETS = new Set<TargetPlatform>(['claude-code', 'cursor', 'codex', 'opencode'])
const GENERATOR_FIXTURE_TARGETS = new Set<TargetPlatform>(ALL_TARGET_PLATFORMS)

const INHERITED_RULES: Partial<Record<TargetPlatform, keyof typeof PLATFORM_VALIDATION_RULES>> = {
  'github-copilot': 'claude-code',
}

function getRuleEntry(platform: TargetPlatform): {
  rules: PlatformRules
  docsBasis: string
} {
  const directRule = PLATFORM_VALIDATION_RULES[platform as keyof typeof PLATFORM_VALIDATION_RULES]
  if (directRule) {
    return {
      rules: directRule,
      docsBasis: 'Official docs audited',
    }
  }

  const inheritedPlatform = INHERITED_RULES[platform]
  if (!inheritedPlatform) {
    throw new Error(`No platform rules available for ${platform}`)
  }

  return {
    rules: PLATFORM_VALIDATION_RULES[inheritedPlatform],
    docsBasis: `Inherits ${humanizePlatformName(inheritedPlatform)} packaging`,
  }
}

const PLATFORM_LABELS: Record<TargetPlatform, string> = {
  'claude-code': 'Claude Code',
  cursor: 'Cursor',
  codex: 'Codex',
  opencode: 'OpenCode',
  'github-copilot': 'GitHub Copilot',
  openhands: 'OpenHands',
  warp: 'Warp',
  'gemini-cli': 'Gemini CLI',
  'roo-code': 'Roo Code',
  cline: 'Cline',
  amp: 'AMP',
}

function humanizePlatformName(platform: TargetPlatform): string {
  return PLATFORM_LABELS[platform]
}

function formatFiles(files: string[], emptyLabel: string): string {
  return files.length > 0 ? files.join(', ') : emptyLabel
}

function getVerificationLabel(platform: TargetPlatform): string {
  const labels: string[] = []

  if (RELEASE_SMOKE_TARGETS.has(platform)) {
    labels.push('Release smoke')
  }

  if (GENERATOR_FIXTURE_TARGETS.has(platform)) {
    labels.push('Generator fixture')
  }

  return labels.join(' + ')
}

export function getPlatformCompatibilityMatrix(): PlatformCompatibilityRow[] {
  return ALL_TARGET_PLATFORMS.map((platform) => {
    const { rules, docsBasis } = getRuleEntry(platform)

    return {
      platform,
      status: PRIMARY_TARGETS.has(platform) ? 'Primary' : 'Beta',
      docsBasis,
      manifest: formatFiles(rules.manifest.files, 'No dedicated manifest'),
      hooks: rules.hooks.supported
        ? formatFiles(rules.hooks.files, 'Supported')
        : 'No documented standalone hook surface',
      mcp: formatFiles(rules.mcp.files, 'None documented'),
      instructions: formatFiles(rules.instructions.files, 'None documented'),
      verification: getVerificationLabel(platform),
    }
  })
}

export function renderCompatibilityMatrixMarkdown(): string {
  const rows = getPlatformCompatibilityMatrix()

  const lines = [
    '<!-- Generated by `bun scripts/generate-compatibility-matrix.ts`. Do not edit by hand. -->',
    '# Compatibility Matrix',
    '',
    'This matrix is generated from the repo-owned platform rules and verification surface.',
    '',
    'Verification labels:',
    '- `Release smoke`: exercised end to end by the real CLI against the real example plugins on the core four.',
    '- `Generator fixture`: covered by the repo build/test fixture layer.',
    '',
    '| Platform | Status | Docs Basis | Manifest | Hooks | MCP | Instructions | Verification |',
    '|----------|--------|------------|----------|-------|-----|--------------|--------------|',
  ]

  for (const row of rows) {
    lines.push(
      `| ${humanizePlatformName(row.platform)} | ${row.status} | ${row.docsBasis} | ${row.manifest} | ${row.hooks} | ${row.mcp} | ${row.instructions} | ${row.verification} |`,
    )
  }

  lines.push(
    '',
    '## Notes',
    '',
    '- The prime-time launch path remains Claude Code, Cursor, Codex, and OpenCode.',
    '- GitHub Copilot currently inherits the Claude Code packaging model in Pluxx rather than using its own separately audited plugin surface.',
    '- Beta platforms are generated and fixture-tested, but they do not yet have the same release-smoke coverage as the core four.',
    '',
  )

  return `${lines.join('\n')}\n`
}
