import { Generator } from '../base'
import type { TargetPlatform } from '../../schema'

export class OpenCodeGenerator extends Generator {
  readonly platform: TargetPlatform = 'opencode'

  async generate(): Promise<void> {
    await Promise.all([
      this.generatePackageJson(),
      this.generatePluginWrapper(),
    ])

    this.copySkills()
    this.copyScripts()
  }

  private async generatePackageJson(): Promise<void> {
    const npmName = this.config.platforms?.opencode?.npmPackage
      ?? `opencode-${this.config.name}`

    const pkg = {
      name: npmName,
      version: this.config.version,
      description: `${this.config.description} (OpenCode plugin)`,
      main: 'index.ts',
      type: 'module',
      keywords: [
        'opencode-plugin',
        ...(this.config.keywords ?? []),
      ],
      author: this.config.author.name,
      license: this.config.license,
      peerDependencies: {
        '@opencode-ai/plugin': '*',
      },
    }

    await this.writeJson('package.json', pkg)
  }

  private async generatePluginWrapper(): Promise<void> {
    const pluginName = toPascalCase(this.config.name) + 'Plugin'
    const envVars = this.getRequiredEnvVars()

    const lines: string[] = [
      `import type { Plugin } from "@opencode-ai/plugin"`,
      '',
      `/**`,
      ` * ${this.config.description}`,
      ` * Generated by plugahh — do not edit manually.`,
      ` */`,
      `export const ${pluginName}: Plugin = async ({ project, client, $, directory }) => {`,
      `  return {`,
    ]

    // Generate session start validation if there are env vars to check
    if (envVars.length > 0) {
      lines.push(`    event: async ({ event }) => {`)
      lines.push(`      if (event.type === "session.idle") return`)
      lines.push(`      if (event.type === "session.created") {`)
      for (const envVar of envVars) {
        lines.push(`        if (!process.env.${envVar}) {`)
        lines.push(`          await client.app.log({`)
        lines.push(`            body: {`)
        lines.push(`              service: "${this.config.name}",`)
        lines.push(`              level: "warn",`)
        lines.push(`              message: "${envVar} is not set. ${this.config.brand?.displayName ?? this.config.name} plugin may not work correctly.",`)
        lines.push(`            },`)
        lines.push(`          })`)
        lines.push(`        }`)
      }
      lines.push(`      }`)
      lines.push(`    },`)
    }

    lines.push(`  }`)
    lines.push(`}`)
    lines.push('')

    await this.writeFile('index.ts', lines.join('\n'))
  }

  private getRequiredEnvVars(): string[] {
    const vars: string[] = []
    if (this.config.mcp) {
      for (const server of Object.values(this.config.mcp)) {
        if (server.auth?.envVar) {
          vars.push(server.auth.envVar)
        }
      }
    }
    return vars
  }
}

function toPascalCase(str: string): string {
  return str
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}
