import { existsSync, readFileSync } from 'fs'
import { resolve } from 'path'
import { MCP_SCAFFOLD_METADATA_PATH, type McpScaffoldMetadata } from './cli/init-from-mcp'
import { collectPermissionRules, type PermissionAction, type ParsedPermissionRule } from './permissions'
import type { PluginConfig } from './schema'
import { parseTomlValue, stripTomlComment } from './toml-lite'

const ACTION_PRIORITY: Record<PermissionAction, number> = {
  allow: 0,
  ask: 1,
  deny: 2,
}

export interface CodexMcpApprovalEntry {
  serverName: string
  toolName: string
}

export interface CodexMcpWildcardGap {
  raw: string
  serverName: string
  reason: string
}

export interface CodexPermissionCompanionPlan {
  hasMcpRules: boolean
  approvalEntries: CodexMcpApprovalEntry[]
  wildcardGaps: CodexMcpWildcardGap[]
}

interface ParsedMcpSelector {
  serverName: string
  toolName: string
}

export function planCodexPermissionCompanion(
  config: PluginConfig,
  rootDir: string,
): CodexPermissionCompanionPlan {
  const mcpRules = collectPermissionRules(config.permissions)
    .filter((rule) => rule.kind === 'MCP')

  if (mcpRules.length === 0) {
    return {
      hasMcpRules: false,
      approvalEntries: [],
      wildcardGaps: [],
    }
  }

  const scaffoldToolInventory = readScaffoldToolInventory(rootDir, config)
  const candidateSelectors = new Set<string>()
  const wildcardGaps = new Map<string, CodexMcpWildcardGap>()

  for (const rule of mcpRules) {
    const selector = parseMcpSelector(rule.pattern)
    if (!selector) continue

    if (selector.toolName !== '*') {
      candidateSelectors.add(`${selector.serverName}.${selector.toolName}`)
      continue
    }

    const knownTools = scaffoldToolInventory.get(selector.serverName)
    if (!knownTools || knownTools.length === 0) {
      wildcardGaps.set(rule.raw, {
        raw: rule.raw,
        serverName: selector.serverName,
        reason: describeWildcardExpansionGap(config, rootDir, selector.serverName),
      })
      continue
    }

    for (const toolName of knownTools) {
      candidateSelectors.add(`${selector.serverName}.${toolName}`)
    }
  }

  const approvalEntries = [...candidateSelectors]
    .map((selector) => {
      const parsed = parseMcpSelector(selector)
      if (!parsed) return null
      const action = resolveEffectiveMcpAction(mcpRules, parsed.serverName, parsed.toolName)
      if (action !== 'allow') return null
      return {
        serverName: parsed.serverName,
        toolName: parsed.toolName,
      } satisfies CodexMcpApprovalEntry
    })
    .filter((entry): entry is CodexMcpApprovalEntry => entry !== null)
    .sort((a, b) => a.serverName.localeCompare(b.serverName) || a.toolName.localeCompare(b.toolName))

  return {
    hasMcpRules: true,
    approvalEntries,
    wildcardGaps: [...wildcardGaps.values()].sort((a, b) => a.raw.localeCompare(b.raw)),
  }
}

export function renderCodexPermissionCompanion(
  plan: CodexPermissionCompanionPlan,
): string | null {
  if (!plan.hasMcpRules) return null
  if (plan.approvalEntries.length === 0 && plan.wildcardGaps.length === 0) return null

  const lines = [
    '# Generated by Pluxx from canonical MCP(...) permission rules.',
    '# Merge the entries below into the active project or user Codex config.toml.',
    '# This file is not auto-loaded from the plugin bundle.',
    '# Only the live-proven allow path is materialized here via approval_mode = "approve".',
    '# ask/deny rules, non-MCP selectors, and migrated skillPolicies remain in .codex/permissions.generated.json.',
  ]

  if (plan.wildcardGaps.length > 0) {
    lines.push('')
    lines.push('# Wildcard MCP rules that Pluxx could not expand into per-tool approval stanzas:')
    for (const gap of plan.wildcardGaps) {
      lines.push(`# - ${gap.raw}: ${gap.reason}`)
    }
  }

  if (plan.approvalEntries.length > 0) {
    for (const entry of plan.approvalEntries) {
      lines.push('')
      lines.push(`[mcp_servers.${toQuotedTomlKey(entry.serverName)}.tools.${toQuotedTomlKey(entry.toolName)}]`)
      lines.push('approval_mode = "approve"')
    }
  }

  return `${lines.join('\n')}\n`
}

export function parseCodexApprovedMcpToolsFromToml(source: string): CodexMcpApprovalEntry[] {
  const approvals = new Map<string, CodexMcpApprovalEntry>()
  let currentSection: CodexMcpApprovalEntry | null = null

  const addApproval = (entry: CodexMcpApprovalEntry): void => {
    approvals.set(`${entry.serverName}.${entry.toolName}`, entry)
  }

  for (const rawLine of source.split(/\r?\n/)) {
    const line = stripTomlComment(rawLine).trim()
    if (!line) continue

    const sectionMatch = line.match(/^\[(.+)\]$/)
    if (sectionMatch) {
      currentSection = parseCodexApprovalSection(sectionMatch[1].trim())
      continue
    }

    const assignmentMatch = line.match(/^([^=]+?)\s*=\s*(.+)$/)
    if (!assignmentMatch) continue

    const key = assignmentMatch[1].trim()
    const parsedValue = parseTomlValue(assignmentMatch[2].trim())

    if (currentSection && key === 'approval_mode' && parsedValue === 'approve') {
      addApproval(currentSection)
      continue
    }

    if (!key.includes('.')) continue
    const entry = parseCodexApprovalAssignment(key, parsedValue)
    if (entry) addApproval(entry)
  }

  return [...approvals.values()]
    .sort((a, b) => a.serverName.localeCompare(b.serverName) || a.toolName.localeCompare(b.toolName))
}

function parseMcpSelector(pattern: string): ParsedMcpSelector | null {
  const trimmed = pattern.trim()
  if (!trimmed) return null

  const dotIndex = trimmed.indexOf('.')
  if (dotIndex === -1) {
    return {
      serverName: trimmed,
      toolName: '*',
    }
  }

  const serverName = trimmed.slice(0, dotIndex).trim()
  const toolName = trimmed.slice(dotIndex + 1).trim()
  if (!serverName || !toolName) return null

  return {
    serverName,
    toolName,
  }
}

function parseCodexApprovalSection(sectionName: string): CodexMcpApprovalEntry | null {
  const tokens = splitTomlDottedPath(sectionName)
  if (tokens.length !== 4) return null
  if (tokens[0] !== 'mcp_servers' || tokens[2] !== 'tools') return null

  return {
    serverName: tokens[1],
    toolName: tokens[3],
  }
}

function parseCodexApprovalAssignment(
  key: string,
  value: unknown,
): CodexMcpApprovalEntry | null {
  if (value !== 'approve') return null

  const tokens = splitTomlDottedPath(key)
  if (tokens.length !== 5) return null
  if (tokens[0] !== 'mcp_servers' || tokens[2] !== 'tools' || tokens[4] !== 'approval_mode') return null

  return {
    serverName: tokens[1],
    toolName: tokens[3],
  }
}

function splitTomlDottedPath(value: string): string[] {
  const parts: string[] = []
  let current = ''
  let inString = false
  let quote = ''

  for (let i = 0; i < value.length; i += 1) {
    const char = value[i]
    if ((char === '"' || char === "'") && value[i - 1] !== '\\') {
      if (!inString) {
        inString = true
        quote = char
      } else if (quote === char) {
        inString = false
        quote = ''
      }
      current += char
      continue
    }

    if (!inString && char === '.') {
      const trimmed = current.trim()
      if (trimmed) parts.push(trimmed)
      current = ''
      continue
    }

    current += char
  }

  const trimmed = current.trim()
  if (trimmed) parts.push(trimmed)

  return parts.map((part) => {
    const parsed = parseTomlValue(part)
    return typeof parsed === 'string' ? parsed : part
  })
}

function resolveEffectiveMcpAction(
  rules: ParsedPermissionRule[],
  serverName: string,
  toolName: string,
): PermissionAction | null {
  let current: PermissionAction | null = null

  for (const rule of rules) {
    if (!matchesMcpRule(rule, serverName, toolName)) continue
    if (!current || ACTION_PRIORITY[rule.action] > ACTION_PRIORITY[current]) {
      current = rule.action
    }
  }

  return current
}

function matchesMcpRule(
  rule: ParsedPermissionRule,
  serverName: string,
  toolName: string,
): boolean {
  const selector = parseMcpSelector(rule.pattern)
  if (!selector) return false
  if (selector.serverName !== serverName) return false
  return selector.toolName === '*' || selector.toolName === toolName
}

function readScaffoldToolInventory(rootDir: string, config: PluginConfig): Map<string, string[]> {
  const metadataPath = resolve(rootDir, MCP_SCAFFOLD_METADATA_PATH)
  if (!existsSync(metadataPath)) return new Map()

  const serverNames = Object.keys(config.mcp ?? {})
  if (serverNames.length !== 1) return new Map()

  try {
    const metadata = JSON.parse(readFileSync(metadataPath, 'utf-8')) as McpScaffoldMetadata
    const toolNames = [...new Set(
      (metadata.tools ?? [])
        .map((tool) => tool?.name)
        .filter((name): name is string => typeof name === 'string' && name.trim() !== ''),
    )].sort()
    if (toolNames.length === 0) return new Map()

    return new Map([[serverNames[0], toolNames]])
  } catch {
    return new Map()
  }
}

function describeWildcardExpansionGap(
  config: PluginConfig,
  rootDir: string,
  serverName: string,
): string {
  const metadataPath = resolve(rootDir, MCP_SCAFFOLD_METADATA_PATH)
  const serverNames = Object.keys(config.mcp ?? {})

  if (serverNames.length === 0) {
    return 'the project does not declare any bundled MCP servers'
  }

  if (serverNames.length > 1) {
    return `${MCP_SCAFFOLD_METADATA_PATH} currently preserves only one imported tool inventory, so this wildcard cannot be expanded safely in a multi-server project`
  }

  if (serverNames[0] !== serverName) {
    return `${MCP_SCAFFOLD_METADATA_PATH} currently maps to bundled server "${serverNames[0]}", not "${serverName}"`
  }

  if (!existsSync(metadataPath)) {
    return `no ${MCP_SCAFFOLD_METADATA_PATH} tool inventory is present for "${serverName}"`
  }

  return `${MCP_SCAFFOLD_METADATA_PATH} could not be parsed into a usable tool inventory for "${serverName}"`
}

function toQuotedTomlKey(value: string): string {
  return JSON.stringify(value)
}
