const PLUGIN_ROOT_REFERENCE_PATTERN = /\$\{(?:PLUGIN_ROOT|PLUXX_PLUGIN_ROOT|CLAUDE_PLUGIN_ROOT|CURSOR_PLUGIN_ROOT|CODEX_PLUGIN_ROOT|OPENCODE_PLUGIN_ROOT)\}(?:[\\/][^\s"'`;$|&<>)]*)?/g

export function quotePluginRootCommandReferences(command: string): string {
  return command.replace(PLUGIN_ROOT_REFERENCE_PATTERN, (match, offset) => {
    const previous = command[offset - 1]
    if (previous === '"' || previous === "'") return match
    return `"${match}"`
  })
}

export function buildHookCommandWrapperScript(command: string, pluginRootVar: string, envFileVar?: string): string {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(pluginRootVar)) {
    throw new Error(`Invalid plugin root environment variable name: ${pluginRootVar}`)
  }

  const serializedCommand = JSON.stringify(quotePluginRootCommandReferences(command))
  const serializedPluginRootVar = JSON.stringify(pluginRootVar)
  const serializedEnvFileVar = JSON.stringify(envFileVar ?? null)

  return [
    '#!/usr/bin/env node',
    'import { appendFileSync, existsSync, readFileSync, statSync } from "node:fs"',
    'import { dirname, resolve } from "node:path"',
    'import { fileURLToPath } from "node:url"',
    'import { spawnSync } from "node:child_process"',
    '',
    'const shellSingleQuote = (input) => `\'${String(input ?? "").replace(/\'/g, `\'"\'"\'`)}\'`',
    `const PLUGIN_ROOT_VAR = ${serializedPluginRootVar}`,
    `const ENV_FILE_VAR = ${serializedEnvFileVar}`,
    `const COMMAND = ${serializedCommand}`,
    '',
    'const scriptPath = fileURLToPath(import.meta.url)',
    'const pluginRoot = resolve(process.env[PLUGIN_ROOT_VAR] || dirname(scriptPath) + "/..")',
    'process.env[PLUGIN_ROOT_VAR] = pluginRoot',
    'process.env.PLUGIN_ROOT = pluginRoot',
    'process.env.PLUXX_PLUGIN_ROOT = pluginRoot',
    '',
    'function readHookPayload() {',
    '  if (process.stdin.isTTY) return null',
    '  try {',
    '    return readFileSync(0, "utf8")',
    '  } catch {',
    '    return null',
    '  }',
    '}',
    '',
    'const hookPayload = readHookPayload()',
    '',
    'const userConfigPath = resolve(pluginRoot, ".pluxx-user.json")',
    'if (existsSync(userConfigPath)) {',
    '  const payload = JSON.parse(readFileSync(userConfigPath, "utf8"))',
    '  const env = payload && typeof payload === "object" && payload.env && typeof payload.env === "object"',
    '    ? payload.env',
    '    : {}',
    '  const envRefs = payload && typeof payload === "object" && payload.envRefs && typeof payload.envRefs === "object"',
    '    ? payload.envRefs',
    '    : {}',
    '',
    '  for (const [key, value] of Object.entries(env)) {',
    '    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue',
    '    process.env[key] = String(value)',
    '    if (ENV_FILE_VAR && process.env[ENV_FILE_VAR]) {',
    '      appendFileSync(process.env[ENV_FILE_VAR], `export ${key}=${shellSingleQuote(String(value))}\\n`)',
    '    }',
    '  }',
    '  for (const [key, envVar] of Object.entries(envRefs)) {',
    '    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue',
    '    if (typeof envVar !== "string" || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(envVar)) continue',
    '    if (!(envVar in process.env)) continue',
    '    const value = String(process.env[envVar])',
    '    process.env[key] = value',
    '    if (ENV_FILE_VAR && process.env[ENV_FILE_VAR]) {',
    '      appendFileSync(process.env[ENV_FILE_VAR], `export ${key}=${shellSingleQuote(value)}\\n`)',
    '    }',
    '  }',
    '}',
    '',
    'function directoryOrNull(value) {',
    '  if (typeof value !== "string" || value.trim() === "") return null',
    '  try {',
    '    const resolved = resolve(value)',
    '    if (resolved === pluginRoot) return null',
    '    if (!existsSync(resolved) || !statSync(resolved).isDirectory()) return null',
    '    return resolved',
    '  } catch {',
    '    return null',
    '  }',
    '}',
    '',
    'function workspaceFromPayload(payload) {',
    '  if (!payload) return null',
    '  let data',
    '  try {',
    '    data = JSON.parse(payload)',
    '  } catch {',
    '    return null',
    '  }',
    '  const values = [',
    '    data.cwd,',
    '    data.workdir,',
    '    data.workspace,',
    '    data.workspaceRoot,',
    '    data.projectRoot,',
    '    data.project_dir,',
    '    data.project && data.project.cwd,',
    '    data.project && data.project.root,',
    '    data.tool_input && data.tool_input.cwd,',
    '    data.tool_input && data.tool_input.workdir,',
    '  ]',
    '  for (const value of values) {',
    '    const directory = directoryOrNull(value)',
    '    if (directory) return directory',
    '  }',
    '  return null',
    '}',
    '',
    'function configureWorkspaceRoot() {',
    '  const explicit = directoryOrNull(process.env.PLUXX_HOOK_WORKSPACE_ROOT)',
    '  if (explicit) {',
    '    process.env.PLUXX_HOOK_WORKSPACE_ROOT = explicit',
    '    return',
    '  }',
    '',
    '  const envCandidates = [',
    '    process.env.CODEX_WORKSPACE_ROOT,',
    '    process.env.CODEX_WORKDIR,',
    '    process.env.CODEX_CWD,',
    '    process.env.CLAUDE_PROJECT_DIR,',
    '    process.env.CLAUDE_CWD,',
    '    process.env.CURSOR_WORKSPACE_ROOT,',
    '    process.env.OPENCODE_WORKSPACE_ROOT,',
    '    process.env.WORKSPACE_ROOT,',
    '    process.env.PROJECT_ROOT,',
    '  ]',
    '  for (const value of envCandidates) {',
    '    const directory = directoryOrNull(value)',
    '    if (directory) {',
    '      process.env.PLUXX_HOOK_WORKSPACE_ROOT = directory',
    '      return',
    '    }',
    '  }',
    '',
    '  const payloadWorkspace = workspaceFromPayload(hookPayload)',
    '  if (payloadWorkspace) process.env.PLUXX_HOOK_WORKSPACE_ROOT = payloadWorkspace',
    '}',
    '',
    'configureWorkspaceRoot()',
    '',
    'function canRun(command) {',
    '  const result = spawnSync(command, ["--version"], { stdio: "ignore" })',
    '  return !result.error && result.status === 0',
    '}',
    '',
    'function findBash() {',
    '  const candidates = ["bash"]',
    '  if (process.platform === "win32") {',
    '    for (const value of [process.env.GIT_BASH, process.env.BASH]) {',
    '      if (value) candidates.push(value)',
    '    }',
    '    candidates.push(',
    '      "C:/Program Files/Git/bin/bash.exe",',
    '      "C:/Program Files/Git/usr/bin/bash.exe",',
    '      "C:/Program Files (x86)/Git/bin/bash.exe",',
    '      "C:/Program Files (x86)/Git/usr/bin/bash.exe",',
    '    )',
    '  }',
    '  for (const candidate of candidates) {',
    '    if (canRun(candidate)) return candidate',
    '  }',
    '  return null',
    '}',
    '',
    'const bash = findBash()',
    'if (!bash) {',
    '  console.error("[pluxx] Cannot run generated hook command because bash was not found.")',
    '  console.error("[pluxx] Install Git Bash on Windows or make bash available on PATH, then rebuild/reinstall the plugin.")',
    '  console.error("[pluxx] Hook command: " + COMMAND)',
    '  process.exit(127)',
    '}',
    '',
    'const spawnOptions = {',
    '  cwd: pluginRoot,',
    '  env: process.env,',
    '}',
    '',
    'if (hookPayload === null) {',
    '  spawnOptions.stdio = "inherit"',
    '} else {',
    '  spawnOptions.stdio = ["pipe", "inherit", "inherit"]',
    '  spawnOptions.input = hookPayload',
    '}',
    '',
    'const result = spawnSync(bash, ["-lc", COMMAND], spawnOptions)',
    '',
    'if (result.error) {',
    '  console.error(`[pluxx] Failed to run generated hook command with ${bash}: ${result.error.message}`)',
    '  process.exit(1)',
    '}',
    '',
    'process.exit(result.status ?? (result.signal ? 128 : 1))',
    '',
  ].join('\n')
}
