import type { McpServer, TargetPlatform } from './schema'
import {
  materializeInstalledPluginOwnedStdioPathForPlatform,
  normalizePluginOwnedStdioPathForPlatform,
} from './mcp-stdio-paths'

type StdioMcpServer = Extract<McpServer, { transport: 'stdio' }>

const ENV_REF_PATTERN = /^\$\{([A-Za-z_][A-Za-z0-9_]*)\}$/

export const MCP_RUNTIME_ENV_SCRIPT_RELATIVE_PATH = 'runtime/pluxx-mcp-env.mjs'

export function collectStdioServerRuntimeEnvVars(
  env: Record<string, string> | undefined,
  runtimeEnvVars: Set<string>,
): Set<string> {
  const output = new Set<string>()

  for (const value of Object.values(env ?? {})) {
    const match = value.match(ENV_REF_PATTERN)
    if (match && runtimeEnvVars.has(match[1])) {
      output.add(match[1])
    }
  }

  return output
}

export function filterRuntimeInheritedStdioEnvRecord(
  input: Record<string, string> | undefined,
  runtimeEnvVars: Set<string>,
): Record<string, string> | undefined {
  const output: Record<string, string> = {}

  for (const [key, value] of Object.entries(input ?? {})) {
    const match = value.match(ENV_REF_PATTERN)
    if (match && runtimeEnvVars.has(match[1])) continue
    output[key] = value
  }

  return Object.keys(output).length > 0 ? output : undefined
}

export function buildRuntimeWrappedStdioMcpCommand(
  server: StdioMcpServer,
  platform: TargetPlatform,
  runtimeEnvVars: Set<string>,
  installedPluginDir?: string,
): { command: string; args: string[] } {
  const normalize = (value: string): string => installedPluginDir
    ? materializeInstalledPluginOwnedStdioPathForPlatform(value, platform, installedPluginDir)
    : normalizePluginOwnedStdioPathForPlatform(value, platform)

  return {
    command: 'node',
    args: [
      normalize(`./${MCP_RUNTIME_ENV_SCRIPT_RELATIVE_PATH}`),
      JSON.stringify([...runtimeEnvVars].sort()),
      '--',
      normalize(server.command),
      ...(server.args ?? []).map(normalize),
    ],
  }
}

export function buildMcpRuntimeEnvScript(): string {
  return [
    '#!/usr/bin/env node',
    'import { existsSync, readFileSync, statSync } from "node:fs"',
    'import { dirname, resolve, relative } from "node:path"',
    'import { homedir } from "node:os"',
    'import { fileURLToPath } from "node:url"',
    'import { spawn } from "node:child_process"',
    '',
    'const ENV_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/',
    'const argv = process.argv.slice(2)',
    'const runtimeEnvVars = new Set(JSON.parse(argv[0] || "[]"))',
    'const separator = argv[1]',
    'const commandArgs = argv.slice(2)',
    '',
    'if (separator !== "--" || commandArgs.length === 0) {',
    '  console.error("[pluxx] Invalid generated MCP runtime launcher arguments.")',
    '  process.exit(64)',
    '}',
    '',
    'const scriptPath = fileURLToPath(import.meta.url)',
    'const pluginRoot = resolve(process.env.PLUXX_PLUGIN_ROOT || dirname(scriptPath) + "/..")',
    'process.env.PLUXX_PLUGIN_ROOT = pluginRoot',
    'process.env.PLUGIN_ROOT = pluginRoot',
    '',
    'function directoryOrNull(value) {',
    '  if (typeof value !== "string" || value.trim() === "") return null',
    '  try {',
    '    const resolved = resolve(value)',
    '    const rel = relative(pluginRoot, resolved)',
    '    if (resolved === pluginRoot || (rel && !rel.startsWith("..") && !rel.startsWith("/") && rel !== "..")) return null',
    '    if (!existsSync(resolved) || !statSync(resolved).isDirectory()) return null',
    '    return resolved',
    '  } catch {',
    '    return null',
    '  }',
    '}',
    '',
    'function workspaceCandidates() {',
    '  return [',
    '    process.env.PLUXX_MCP_WORKSPACE_ROOT,',
    '    process.env.PLUXX_WORKSPACE_ROOT,',
    '    process.env.PLUXX_HOOK_WORKSPACE_ROOT,',
    '    process.env.CODEX_WORKSPACE_ROOT,',
    '    process.env.CODEX_WORKDIR,',
    '    process.env.CODEX_CWD,',
    '    process.env.CLAUDE_PROJECT_DIR,',
    '    process.env.CLAUDE_CWD,',
    '    process.env.CURSOR_WORKSPACE_ROOT,',
    '    process.env.OPENCODE_WORKSPACE_ROOT,',
    '    process.env.WORKSPACE_ROOT,',
    '    process.env.PROJECT_ROOT,',
    '    process.env.INIT_CWD,',
    '    process.cwd(),',
    '    process.env.PWD,',
    '  ].map(directoryOrNull).filter(Boolean)',
    '}',
    '',
    'function hasWorkspaceBoundary(directory) {',
    '  return existsSync(resolve(directory, ".git"))',
    '    || existsSync(resolve(directory, ".hg"))',
    '    || existsSync(resolve(directory, "package.json"))',
    '    || existsSync(resolve(directory, "pyproject.toml"))',
    '    || existsSync(resolve(directory, "deno.json"))',
    '}',
    '',
    'function findWorkspaceContext() {',
    '  const home = resolve(homedir())',
    '  const seen = new Set()',
    '  let fallbackRoot = null',
    '  for (const start of workspaceCandidates()) {',
    '    if (!fallbackRoot) fallbackRoot = start',
    '    let current = start',
    '    while (current && !seen.has(current)) {',
    '      seen.add(current)',
    '      if (current === home) break',
    '      const envPath = resolve(current, ".env")',
    '      if (existsSync(envPath)) return { root: current, envPath }',
    '      if (hasWorkspaceBoundary(current)) return { root: current, envPath: null }',
    '      const parent = dirname(current)',
    '      if (parent === current) break',
    '      current = parent',
    '    }',
    '    return { root: start, envPath: null }',
    '  }',
    '  return fallbackRoot ? { root: fallbackRoot, envPath: null } : null',
    '}',
    '',
    'function stripInlineComment(value) {',
    '  let quote = null',
    '  for (let index = 0; index < value.length; index += 1) {',
    '    const char = value[index]',
    '    const previous = value[index - 1]',
    '    if ((char === "\\"" || char === "\'") && previous !== "\\\\") {',
    '      quote = quote === char ? null : quote || char',
    '    }',
    '    if (!quote && char === "#" && /\\s/.test(previous || "")) {',
    '      return value.slice(0, index).trimEnd()',
    '    }',
    '  }',
    '  return value',
    '}',
    '',
    'function decodeEnvValue(raw) {',
    '  const trimmed = stripInlineComment(raw.trim())',
    '  if (trimmed.length >= 2 && trimmed.startsWith("\'") && trimmed.endsWith("\'")) {',
    '    return trimmed.slice(1, -1)',
    '  }',
    '  if (trimmed.length >= 2 && trimmed.startsWith("\\"") && trimmed.endsWith("\\"")) {',
    '    return trimmed.slice(1, -1)',
    '      .replace(/\\\\n/g, "\\n")',
    '      .replace(/\\\\r/g, "\\r")',
    '      .replace(/\\\\t/g, "\\t")',
    '      .replace(/\\\\\\"/g, "\\"")',
    '      .replace(/\\\\\\\\/g, "\\\\")',
    '  }',
    '  return trimmed',
    '}',
    '',
    'function parseDotEnv(source) {',
    '  const values = {}',
    '  for (const rawLine of source.split(/\\r?\\n/)) {',
    '    let line = rawLine.trim()',
    '    if (!line || line.startsWith("#")) continue',
    '    if (line.startsWith("export ")) line = line.slice("export ".length).trimStart()',
    '    const equals = line.indexOf("=")',
    '    if (equals === -1) continue',
    '    const key = line.slice(0, equals).trim()',
    '    if (!ENV_NAME.test(key)) continue',
    '    values[key] = decodeEnvValue(line.slice(equals + 1))',
    '  }',
    '  return values',
    '}',
    '',
    'function loadWorkspaceEnv() {',
    '  const match = findWorkspaceContext()',
    '  if (!match) return',
    '  process.env.PLUXX_MCP_WORKSPACE_ROOT = match.root',
    '  if (!process.env.PLUXX_WORKSPACE_ROOT) process.env.PLUXX_WORKSPACE_ROOT = match.root',
    '  if (!match.envPath) return',
    '  const values = parseDotEnv(readFileSync(match.envPath, "utf8"))',
    '  for (const name of runtimeEnvVars) {',
    '    if (!ENV_NAME.test(name)) continue',
    '    if (Object.prototype.hasOwnProperty.call(values, name)) {',
    '      process.env[name] = String(values[name])',
    '    }',
    '  }',
    '}',
    '',
    'function loadInstalledUserConfig() {',
    '  const path = resolve(pluginRoot, ".pluxx-user.json")',
    '  if (!existsSync(path)) return',
    '  let payload',
    '  try {',
    '    payload = JSON.parse(readFileSync(path, "utf8"))',
    '  } catch {',
    '    return',
    '  }',
    '  const env = payload && typeof payload === "object" && payload.env && typeof payload.env === "object" ? payload.env : {}',
    '  const envRefs = payload && typeof payload === "object" && payload.envRefs && typeof payload.envRefs === "object" ? payload.envRefs : {}',
    '  for (const [key, value] of Object.entries(env)) {',
    '    if (!ENV_NAME.test(key) || runtimeEnvVars.has(key)) continue',
    '    process.env[key] = String(value)',
    '  }',
    '  for (const [key, envVar] of Object.entries(envRefs)) {',
    '    if (!ENV_NAME.test(key) || runtimeEnvVars.has(key)) continue',
    '    if (typeof envVar !== "string" || !ENV_NAME.test(envVar)) continue',
    '    if (Object.prototype.hasOwnProperty.call(process.env, envVar)) {',
    '      process.env[key] = String(process.env[envVar])',
    '    }',
    '  }',
    '}',
    '',
    'function expandPluginRoot(value) {',
    '  return String(value).replace(/\\$\\{(?:PLUGIN_ROOT|PLUXX_PLUGIN_ROOT|CLAUDE_PLUGIN_ROOT|CURSOR_PLUGIN_ROOT|CODEX_PLUGIN_ROOT|OPENCODE_PLUGIN_ROOT)\\}/g, pluginRoot)',
    '}',
    '',
    'loadInstalledUserConfig()',
    'loadWorkspaceEnv()',
    '',
    'const command = expandPluginRoot(commandArgs[0])',
    'const args = commandArgs.slice(1).map(expandPluginRoot)',
    'const child = spawn(command, args, {',
    '  cwd: pluginRoot,',
    '  env: process.env,',
    '  stdio: "inherit",',
    '  detached: process.platform !== "win32",',
    '})',
    'const signalExitCodes = { SIGINT: 130, SIGTERM: 143, SIGHUP: 129 }',
    'let forwardedSignal = null',
    '',
    'function killChild(signal) {',
    '  if (!child.pid) return',
    '  try {',
    '    if (process.platform === "win32") child.kill(signal)',
    '    else process.kill(-child.pid, signal)',
    '  } catch {',
    '    child.kill(signal)',
    '  }',
    '}',
    '',
    'for (const signal of Object.keys(signalExitCodes)) {',
    '  process.once(signal, () => {',
    '    forwardedSignal = signal',
    '    killChild(signal)',
    '    process.exit(signalExitCodes[signal] || 1)',
    '  })',
    '}',
    '',
    'child.on("error", (error) => {',
    '  console.error(`[pluxx] Failed to start MCP stdio command: ${error.message}`)',
    '  process.exit(1)',
    '})',
    '',
    'child.on("exit", (code, signal) => {',
    '  if (forwardedSignal) {',
    '    process.exit(signalExitCodes[forwardedSignal] || 1)',
    '  }',
    '  if (signal) {',
    '    process.kill(process.pid, signal)',
    '    return',
    '  }',
    '  process.exit(code ?? 1)',
    '})',
    '',
  ].join('\n')
}
